# DataFrame Creation

Now that we have successfully collected the data from Ergast-Jolpica API we will proceed to form a single dataframe to be used in Exploratory Data Analysis(EDA) stage.

The csv files were imported separately to keep tabs and not miss out on uploading any

In [2]:
import pandas as pd

#Weather data
df_weather = pd.read_csv(r'C:\Users\NATHAN\f1_race_weather_all_seasons_2019_to_2024.csv')

#Race Results
df_results = pd.read_csv(r'C:\Users\NATHAN\race_results_all_seasons.csv')

#Pitstop data
df_pitstops = pd.read_csv(r'C:\Users\NATHAN\pitstop_data.csv')

#Laps data
df_laps = pd.read_csv(r'C:\Users\NATHAN\f1_lap_times_2019_2024.csv')

In [3]:
#Having a look at the weather data
print('Shape of the data: ')
print(df_weather.shape)
df_weather.head()

Shape of the data:
(128, 10)

,Race Name,Date,Latitude,Longitude,Weather,Temperature (°C),Humidity (%),Wind Speed (m/s),Rain (mm),Year
0,Australian Grand Prix,2019-03-17,-37.8497,144.96800,broken clouds,17.76,67,0.89,No rain,2019
1,Bahrain Grand Prix,2019-03-31,26.0325,50.51060,clear sky,21.05,72,5.45,No rain,2019
2,Chinese Grand Prix,2019-04-14,31.3389,121.22000,clear sky,2.99,75,4.00,No rain,2019
3,Azerbaijan Grand Prix,2019-04-28,40.3725,49.85330,light intensity shower rain,4.97,75,12.35,No rain,2019
4,Spanish Grand Prix,2019-05-12,41.5700,2.26111,clear sky,9.61,85,3.09,No rain,2019

In [4]:
#Having a look at the race results data
print('Shape of the data: ')
print(df_results.shape)
df_results.head()

Shape of the data:
(2559, 12)

,Year,Round,Race Name,Driver Name,Constructor Name,Grid Position,Final Position,Time,Fastest Lap Time,Points,Status,Number of Laps
0,2019,1,Australian Grand Prix,Valtteri Bottas,Mercedes,2,1,1:25:27.325,1:25.580,26.0,Finished,58
1,2019,1,Australian Grand Prix,Lewis Hamilton,Mercedes,1,2,+20.886,1:26.057,18.0,Finished,58
2,2019,1,Australian Grand Prix,Max Verstappen,Red Bull,4,3,+22.520,1:26.256,15.0,Finished,58
3,2019,1,Australian Grand Prix,Sebastian Vettel,Ferrari,3,4,+57.109,1:27.954,12.0,Finished,58
4,2019,1,Australian Grand Prix,Charles Leclerc,Ferrari,5,5,+58.203,1:26.926,10.0,Finished,58

In [5]:
#Having a look at the pitstop data
print('Shape of the data: ')
print(df_pitstops.shape)
df_pitstops.rename(columns = {'Season' : 'Year'},inplace=True)
df_pitstops.head()

Shape of the data:
(3429, 8)

,Race Name,Year,Round,Driver ID,Lap,Stop,Time,Duration
0,Australian Grand Prix,2019,1,kubica,1,1,16:15:28,32.997
1,Australian Grand Prix,2019,1,ricciardo,1,1,16:15:30,33.027
2,Australian Grand Prix,2019,1,raikkonen,12,1,16:31:50,23.299
3,Australian Grand Prix,2019,1,hulkenberg,13,1,16:33:19,21.588
4,Australian Grand Prix,2019,1,perez,13,1,16:33:28,23.234

In [6]:
#Having a look at laps data
print('Shape of the data: ')
print(df_laps.shape)
df_laps.head()

Shape of the data:
(12620, 7)

,Year,Round,Race Name,Lap Number,Driver ID,Position,Lap Time
0,2019,1,Australian Grand Prix,1,bottas,1,1:33.813
1,2019,1,Australian Grand Prix,1,hamilton,2,1:34.887
2,2019,1,Australian Grand Prix,1,vettel,3,1:35.626
3,2019,1,Australian Grand Prix,1,max_verstappen,4,1:36.291
4,2019,1,Australian Grand Prix,1,leclerc,5,1:37.042

In [7]:
df_laps['Driver ID'].unique()

array(['bottas', 'hamilton', 'vettel', 'max_verstappen', 'leclerc',
       'kevin_magnussen', 'grosjean', 'hulkenberg', 'raikkonen', 'norris',
       'albon', 'perez', 'stroll', 'sainz', 'kvyat', 'giovinazzi',
       'gasly', 'russell', 'kubica', 'ricciardo', 'ocon', 'latifi',
       'aitken', 'pietro_fittipaldi', 'alonso', 'tsunoda',
       'mick_schumacher', 'mazepin', 'zhou', 'de_vries', 'sargeant',
       'piastri', 'lawson', 'bearman', 'colapinto'], dtype=object)

#Merging the Dataframes

We merge the above dataframes into one dataframe on which EDA, Feature Enginering etc. that is, all the necessary steps will be performed, before feeding it to the Machine Learning Model

In [8]:
#Since the results dataframe doesn't have a Driver ID column, we will create it

#Getting the driver_list from the laps dataframe
driver_list = df_laps['Driver ID'].unique()

#Extracting the last name from the driver names and creating a new feature to store
df_results['Driver ID'] = df_results['Driver Name'].str.lower().str.split().str[-1]

#Ensure that the Driver ID matches the format of Driver ID in df_laps
df_results['Driver ID'] = df_results['Driver ID'].apply(lambda x: x if x in driver_list else None)

#Check the result
df_results

,Year,Round,Race Name,Driver Name,Constructor Name,Grid Position,Final Position,Time,Fastest Lap Time,Points,Status,Number of Laps,Driver ID
0,2019,1,Australian Grand Prix,Valtteri Bottas,Mercedes,2,1,1:25:27.325,1:25.580,26.0,Finished,58,bottas
1,2019,1,Australian Grand Prix,Lewis Hamilton,Mercedes,1,2,+20.886,1:26.057,18.0,Finished,58,hamilton
2,2019,1,Australian Grand Prix,Max Verstappen,Red Bull,4,3,+22.520,1:26.256,15.0,Finished,58,None
3,2019,1,Australian Grand Prix,Sebastian Vettel,Ferrari,3,4,+57.109,1:27.954,12.0,Finished,58,vettel
4,2019,1,Australian Grand Prix,Charles Leclerc,Ferrari,5,5,+58.203,1:26.926,10.0,Finished,58,leclerc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2554,2024,24,Abu Dhabi Grand Prix,Kevin Magnussen,Haas F1 Team,14,16,NaN,1:25.637,0.0,+1 Lap,57,None
2555,2024,24,Abu Dhabi Grand Prix,Liam Lawson,RB F1 Team,12,17,NaN,1:28.751,0.0,Engine,55,lawson
2556,2024,24,Abu Dhabi Grand Prix,Valtteri Bottas,Sauber,9,18,NaN,1:29.482,0.0,Collision damage,30,bottas
2557,2024,24,Abu Dhabi Grand Prix,Franco Colapinto,Williams,20,19,NaN,1:29.411,0.0,Engine,26,colapinto
2558,2024,24,Abu Dhabi Grand Prix,Sergio Pérez,Red Bull,10,20,NaN,NaN,0.0,Collision,0,None

In [9]:
#Step 1 : Merge df_laps and df_results on 'Race Name', 'Year' and 'Driver ID'
df_combined = pd.merge(df_laps, df_results, on=['Race Name', 'Year' ,'Driver ID'],how = 'left')

#Step 2 : Merge the combined dataframe with df_pitstops on 'Race Name', 'Year' and 'Driver ID'
df_combined = pd.merge(df_combined, df_pitstops, on = ['Race Name','Year','Driver ID'],how = 'left')

#Step 3 : Merge the combined dataframe with df_weather on 'Race Name' and 'Year'
df_combined = pd.merge(df_combined, df_weather, on = ['Race Name','Year'], how='left')

#Display the first few rows of the merged dataframe to check
df_combined

,Year,Round_x,Race Name,Lap Number,Driver ID,Position,Lap Time,Round_y,Driver Name,Constructor Name,...,Time_y,Duration,Date,Latitude,Longitude,Weather,Temperature (°C),Humidity (%),Wind Speed (m/s),Rain (mm)
0,2019,1,Australian Grand Prix,1,bottas,1,1:33.813,1.0,Valtteri Bottas,Mercedes,...,16:47:33,22.014,2019-03-17,-37.8497,144.9680,broken clouds,17.76,67,0.89,No rain
1,2019,1,Australian Grand Prix,1,hamilton,2,1:34.887,1.0,Lewis Hamilton,Mercedes,...,16:35:52,21.515,2019-03-17,-37.8497,144.9680,broken clouds,17.76,67,0.89,No rain
2,2019,1,Australian Grand Prix,1,vettel,3,1:35.626,1.0,Sebastian Vettel,Ferrari,...,16:34:28,21.995,2019-03-17,-37.8497,144.9680,broken clouds,17.76,67,0.89,No rain
3,2019,1,Australian Grand Prix,1,max_verstappen,4,1:36.291,NaN,NaN,NaN,...,16:50:47,21.157,2019-03-17,-37.8497,144.9680,broken clouds,17.76,67,0.89,No rain
4,2019,1,Australian Grand Prix,1,leclerc,5,1:37.042,1.0,Charles Leclerc,Ferrari,...,16:55:26,22.306,2019-03-17,-37.8497,144.9680,broken clouds,17.76,67,0.89,No rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18157,2024,23,Qatar Grand Prix,6,sainz,6,1:27.634,23.0,Carlos Sainz,Ferrari,...,NaN,NaN,2024-12-01,25.4900,51.4542,scattered clouds,20.97,72,3.43,No rain
18158,2024,23,Qatar Grand Prix,6,perez,7,1:27.827,NaN,NaN,NaN,...,NaN,NaN,2024-12-01,25.4900,51.4542,scattered clouds,20.97,72,3.43,No rain
18159,2024,23,Qatar Grand Prix,6,hamilton,8,1:28.084,23.0,Lewis Hamilton,Mercedes,...,NaN,NaN,2024-12-01,25.4900,51.4542,scattered clouds,20.97,72,3.43,No rain
18160,2024,23,Qatar Grand Prix,6,tsunoda,9,1:28.679,23.0,Yuki Tsunoda,RB F1 Team,...,NaN,NaN,2024-12-01,25.4900,51.4542,scattered clouds,20.97,72,3.43,No rain
18161,2024,23,Qatar Grand Prix,6,kevin_magnussen,10,1:28.533,NaN,NaN,NaN,...,NaN,NaN,2024-12-01,25.4900,51.4542,scattered clouds,20.97,72,3.43,No rain

In [10]:
#Getting the number of pit stops for each driver
pit_stops = df_combined.groupby(['Year','Race Name','Driver ID'])['Stop'].transform('nunique')

#Broadcasting the data
df_combined['Pit Stops'] = pit_stops

#Getting the number of pit stops for each driver
df_combined['Pit Stops'].value_counts()

Pit Stops
2    9632
1    6960
3     999
0     491
4      80
Name: count, dtype: int64

In [11]:
df_combined[['Driver ID','Pit Stops']].head()

        Driver ID  Pit Stops
0          bottas          1
1        hamilton          1
2          vettel          1
3  max_verstappen          1
4         leclerc          1

In [13]:
#Saving this dataframe to a CSV file
df_combined.to_csv('f1_combined_data_final.csv',index = False)